### ISSUE TITLE
2024.11.x

### ISSUE THREAD

**Issue by edwardtfn** [khenderick/esphome-legacy-addons#6]
Have you stopped maintaining this repo? I don't see 2024.10 and 2024.11 available...
Could I help in some way?

**Comment by khenderick** [comment]
It's still maintained (doesn't take much work :sweat_smile:). 

The versions are available:
* https://github.com/khenderick/esphome-legacy-addons/tree/main/esphome-2024-11
* https://github.com/khenderick/esphome-legacy-addons/tree/main/esphome-2024-10

You should see them here in the repo, and I see them also in the add-on store. Note that it seems to sort them strictly alphabetically, so not based on number. So those are somewhere in the middle above `2024.2`.

![image](https://github.com/user-attachments/assets/948b45a0-0f34-4470-a428-33fdd8f8503f)

Can you let me know if you can see them? If not, can you post a screenshot of the list or check if there are any errors in your HA logs that mention the repo?

**Comment by edwardtfn** [comment]
Sorry, I was fooled by the sorting... Now I found and installed it 
Thanks a lot!

**Comment by khenderick** [comment]
No problem, I'm glad you find the repo useful :+1:
